from typing import Protocol

from src.domain.models.project import Project
from src.domain.models.region import TranslationRegion


class IProjectRepository(Protocol):
    def save(self, project: Project) -> None: ...
    def get(self, project_id: str) -> Project | None: ...


class ITranslationRegionRepository(Protocol):
    def save(self, region: TranslationRegion) -> None: ...
    def get(self, region_id: str) -> TranslationRegion | None: ...
    def delete(self, region_id: str) -> None: ...
    def get_by_page(self, project_id: str, page_id: int) -> list[TranslationRegion]: ...
    def get_all(self, project_id: str) -> list[TranslationRegion]: ...
    def count(self, project_id: str) -> int: ...


class IGlossaryRepository(Protocol):
    from src.domain.models.glossary import Glossary
    def save(self, glossary: Glossary) -> None: ...
    def get(self, glossary_id: str) -> Glossary | None: ...
    def delete(self, glossary_id: str) -> None: ...


from src.domain.interfaces.translation_memory import ITranslationMemoryRepository

class IUnitOfWork(Protocol):
    def __enter__(self) -> 'IUnitOfWork': ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
    @property
    def region_repository(self) -> ITranslationRegionRepository: ...
    @property
    def translation_memory_repository(self) -> ITranslationMemoryRepository: ...

class IProjectPersistenceFactory(Protocol):
    def create_unit_of_work(self, db_path: str) -> IUnitOfWork: ...

    def create_project_repository(self, db_path: str) -> IProjectRepository:
        pass

    def create_region_repository(self, db_path: str) -> ITranslationRegionRepository:
        pass

    def create_glossary_repository(self, db_path: str) -> IGlossaryRepository:
        pass

    def backup(self, db_path: str, dest_path: str) -> None:
        pass
